EXP:
  NAME: faces
  SEED: 2020
  OUT_DIR: results/faces

SR:
  SCALE: 2
  PATCH_SIZE_LR: 32
  BATCH_PER_GPU: 16
  MODEL: ESRGAN # ESRGAN or UPSCALER

OPT:
  MAX_ITER: 300000

OPT_CYC:
  LR_D: 0.0001
  LR_G: 0.0001
  TYPE: ADAM
  MOMENTUM: 0.9
  BETAS_D: [0.5, 0.999]
  BETAS_G: [0.5, 0.999]
  LR_MILESTONE: [100000, 180000, 240000, 280000]
  LR_DECAY: 0.5
  LOSS:
    CYC_WEIGHT: 1
    IDT_WEIGHT: 2
    GEO_WEIGHT: 1
    D_SR_WEIGHT: 0.1
  IDT_INPUT: clean # corrupted or clean

OPT_SR:
  WARMUP: 5000
  LR_D: 0.0001
  LR_G: 0.0001
  TYPE: ADAM
  MOMENTUM: 0.9
  BETAS_D: [0.9, 0.999]
  BETAS_G: [0.9, 0.999]
  LR_MILESTONE: [100000, 180000, 240000, 280000]
  LR_DECAY: 0.9
  LOSS:
    PIXEL_WEIGHT: 0.01
    VGG_WEIGHT: 1
    GAN_WEIGHT: 0.005

PRETRAINED:
  LR_D: False
  LR_G: False
  HR_D: False
  HR_G: False
  STRICT: False

RESUME:
  LR_GAN: False
  HR_GAN: False

DATA:
  FOLDER: /mnt/workspace/Face-and-Image-super-resolution/Dataset
  NUM_WORKERS: 8
  IMG_RANGE: 1 # for ESRGAN, set it to 1
  IMG_MEAN_SHIFT: False # for ESRGAN, set it to False
  RGB: True
